name: Scheduled Workflow

on:
  schedule:
    - cron: "* * * * *"  # cada 1 minuto (solo para prueba)

jobs:
  schedule-job:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar mensaje
        run: echo "Ejecución programada"
